services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/code
      - frontend_node_modules:/code/node_modules
    depends_on:
      - backend
    env_file:
      - .env
    tty: true

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/code
      - ./backend/static:/code/static
      - ./backend/media:/code/media
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  frontend_node_modules:
  media:
  static:
  pgadmin_data:


  # http://localhost:5050
